[package]
name = "laz2omap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
fastrand = "2.1.1"
kiddo = { version = "4.2.1", features = ["immutable"] }
las = { version = "0.9.1", features = ["laz"] }
spade = "2.12.1"
tiff = "0.9.1"
indicatif = "0.17.8"
geo = "0.29.3"
