[package]
name = "laz2omap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.0", features = ["derive"] }
kiddo = { version = "4.2.0", features = ["immutable"] }
las = { version = "0.8.2", features = ["laz"] }
rand = "0.8.5"
rustc-hash = "2.0.0"
serde = { version = "1.0.208", features = ["derive"]}
tiff = "0.9.1"
