[package]
name = "omap_maker"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
authors = ["Øyvind Hjermstad"]
description = "An application for generating orienteering maps from lidar data"
repository = "https://github.com/yvind/omapmaker"

[features]
default = []
deep-learning = ["stream-svf-slope"]
stream-svf-slope = [
    "dep:burn",
    "dep:burn-store",
    "dep:burn-onnx",
    "dep:serde",
    "dep:sha2",
    "dep:toml",
]

[[bin]]
name = "OmapMaker"
path = "src/main.rs"

[dependencies]
# gui
eframe = "0.35"
egui_autocomplete = { git = "https://github.com/yvind/egui_autocomplete" }
egui_double_slider = "3.0.0"

# choose files
rfd = "0.17.2"

# slippy map tiles
walkers = { git = "https://github.com/yvind/walkers" }

# projections
proj-wkt = "0.10.0"
proj-core = "0.10.0"

# delaunay and interpolation
spade = "2.15.1"

# easy parallelization
rayon = "1.12.0"

# geometry
geo = "0.33.1"
rstar = "0.13.0"

# read/write las/laz/copc
las = { version = "0.11.0", features = ["laz-parallel"] }
copc_converter = "0.11.0"

# write omap files
omap = { version = "0.12.0", features = ["geo_ref"] }

# better errors
thiserror = "2"
anyhow = "1"

# logging warnings and non-panic errors
log = "0.4"

# writing geotiffs
geotiff-writer = "0.7.0"

# needed??
ndarray = "0.17.2"

[dependencies.burn]
version = "=0.22.0-pre.3"
optional = true
default-features = false
features = ["std", "wgpu", "fusion"]

[dependencies.burn-store]
version = "=0.22.0-pre.3"
optional = true
default-features = false
features = ["std"]

[build-dependencies]
serde = { version = "1", optional = true, features = ["derive"] }
sha2 = { version = "0.10", optional = true }
toml = { version = "1", optional = true }

[build-dependencies.burn-onnx]
version = "=0.22.0-pre.3"
optional = true
default-features = false
features = ["import"]
