pub enum SymbolKind {
    Contour,
    SlopeLineContour,
    ContourBasemap,
    ContourIndex,
    ContourValue,
    FormLine,
    SlopeLineFormLine,
    EarthBank,
    EarthBankMin,
    EarthBankLine,
    EarthBankTag,
    EarthWall,
    EarthWallRetaining,
    EarthWallRuined,
    ErosionGully,
    ErosionGullySmall,
    KnollSmall,
    ElongatedKnollSmall,
    DepressionSmall,
    Pit,
    BrokenGround,
    BrokenGroundSingle,
    BrokenGroundVery,
    ProminentLandformFeature,
    CliffImpassable,
    CliffImpassableMin,
    CliffImpassableLine,
    CliffImpassableTag,
    Cliff,
    CliffMin,
    CliffTagged,
    CliffTaggedMin,
    PitCaveRocky,
    PitDangerous,
    Boulder,
    BoulderEnlarged,
    BoulderLarge,
    BoulderGigantic,
    BoulderCluster,
    BoulderClusterEnlarged,
    BoulderField,
    BoulderFieldSingle,
    BoulderFieldSingleEnlarged,
    BoulderFieldDense,
    StonyGroundSlow,
    StonyGroundSingle,
    StonyGroundWalk
    StonyGroundFight,
    SandyGround,
    BareRock,
    Trench,
    WaterUncrossableAreaLine,
    WaterUncrossableArea,
    WaterUncrossableAreaLine70,
    WaterUncrossableArea70,
    WaterUncrossableLine,
    WaterShallowAreaLine,
    WaterShallowAreaDashed,
    WaterShallowArea,
    WaterShallowLine,
    WaterShallowDashed,
    WaterShallowArea100,
    Waterhole,
    StreamCrossable,
    StreamCrossableSmall,
    StreamSeasonal,
    MarshUncrossableAreaLine,
    MarshUncrossableArea,
    Marsh,
    MarshMin,
    MarshNarrow,
    MarshIndistinct,
    MarshIndistinctMin,
    Well,
    Spring,
    ProminentWaterFeature,
    OpenLand,
    OpenLandScatteredTrees,
    OpenLandScatteredBushes,
    OpenLandRough,
    OpenLandRoughScatteredTrees,
    OpenLandRoughScatteredBushes,
    Forest,
    VegetationSlow,
    VegetationSlowDirectional,
    VegetationSlowUnderGrowth,
    VegetationWalk,
    VegetationWalkDirectional,
    VegetationWalkDirectionalSlow,
    VegetationWalkUnderGrowth,
    VegetationFight,
    VegetationFightDirectional,
    VegetationFightDirectionalWalk,
    VegetationFightDirectionalSlow,
    VegetationFightMin,
    CultivatedLand,
    Orchard,
    OrchardRough,
    Vineyard,
    VineyardRough,
    CultivationBoundaryDistinct,
    VegetationBoundaryDistinct,
    VegetationBoundaryDistinctBlack,
    Tree,
    Bush,
    ProminentVegetationFeature,
    PavedAreaAreaLine,
    PavedAreaArea,
    PavedAreaLine,
    PavedRoad,
    PavedRoadWide,
    Road,
    TrackVehicle,
    Path,
    PathSmall,
    PathIndistinct,
    RideNarrow,
    RideNarrowOpen,
    RideNarrowWhite,
    RideNarrowSlow,
    RideNarrowWalk,
    Railway,
    RailwayOOB,
    Powerline,
    PowerlineMajorMin,
    PowerlineMajor,
    PowerlineMajorBig,
    Bridge,
    BridgeMin,
    BridgeFoot,
    StoneWall,
    StoneWallRetaining,
    StoneWallRuined,
    StoneWallImpassable,
    Fence,
    FenceRuined,
    FenceImpassable,
    FenceGate,
    PrivateProperty,
    PrivatePropertyLine,
    Building,
    BuildingMin,
    BuildingLargeAreaLine,
    BuildingLargeArea,
    BuildingLargeLine,
    CanopyAreaLine,
    CanopyArea,
    CanopyLine,
    Ruin,
    RuinMin,
    TowerHigh,
    TowerSmall,
    Cairn,
    FodderRack,
    ProminentLineFeature,
    ProminentLineFeatureImpassable,
    ProminentManMadeFeatureO,
    ProminentManMadeFeatureX,
    Stairway,
    MagneticNorthBlack,
    MagneticNorthBlue,
    RegistrationMark,
    SpotHeightDot,
    SpotHeightValue,
    ControlNumber,
    OrienteeringCourse,
}

pub enum SymbolType {
    Point = 1,
    Line = 2,
    Area = 4,
    Text = 8,
    Combined = 16,
}

impl SymbolKind {
    pub fn get_symbol(&self) -> Symbol {
        match &self {

        }
    }
}

pub struct Symbol {
    pub code: u16,
    pub colors: Vec<ColorKind>,
    pub xml: String,
    pub symbol_type: SymbolType,
}