pub const TILE_SIZE_METERS_USIZE: usize = 256;
pub const MIN_TILE_OVERLAP_METERS_USIZE: usize = 14;
pub const INV_CELL_SIZE_METERS_USIZE: usize = 2;
pub const STANDARD_CELL_SIZE_METERS: f64 = 0.5;
pub const SIMPLIFICATION_DIST: f64 = 0.1;

pub const MIN_GRAD_LENGTH: f32 = 1.0;

pub const TILE_SIZE_PIXELS: usize = INV_CELL_SIZE_METERS_USIZE * TILE_SIZE_METERS_USIZE;
pub const CELL_SIZE_METERS: f64 = STANDARD_CELL_SIZE_METERS;
pub const TILE_SIZE_METERS: f64 = TILE_SIZE_METERS_USIZE as f64;
pub const MIN_TILE_OVERLAP_METERS: f64 = MIN_TILE_OVERLAP_METERS_USIZE as f64;

pub const ADJUSTMENT_TILE_SIZE_METERS: f64 = 480.;
